name: INTEGRATE

on:
  pull_request:
    branches: ['prod', 'master']

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install main directory
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        uses: cypress-io/github-action@master
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 120
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

